-- ============================================================================
-- Pieces
-- One-of-one catalog inventory managed by Onesbryne admins.
-- ============================================================================
CREATE TABLE public.pieces (
    id uuid PRIMARY KEY DEFAULT extensions.gen_random_uuid (),
    code_number integer GENERATED BY DEFAULT AS IDENTITY,
    code text GENERATED ALWAYS AS ('OB-' || lpad(code_number::text, 3, '0')) STORED,
    name text NOT NULL,
    brand text,
    category_slug text NOT NULL REFERENCES public.categories (slug) ON UPDATE CASCADE ON DELETE RESTRICT,
    size_label public.piece_size NOT NULL,
    condition_label public.piece_condition,
    price_cents integer NOT NULL,
    description text NOT NULL,
    status text NOT NULL DEFAULT 'draft',
    published_at timestamptz,
    sold_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pieces_code_number_positive_check CHECK (code_number > 0),
    CONSTRAINT pieces_code_number_unique UNIQUE (code_number),
    CONSTRAINT pieces_code_unique UNIQUE (code),
    CONSTRAINT pieces_name_length_check CHECK (char_length(btrim(name)) BETWEEN 1 AND 180),
    CONSTRAINT pieces_brand_length_check CHECK (brand IS NULL OR char_length(btrim(brand)) BETWEEN 1 AND 120),
    CONSTRAINT pieces_price_cents_check CHECK (price_cents >= 0),
    CONSTRAINT pieces_description_length_check CHECK (char_length(btrim(description)) BETWEEN 1 AND 5000),
    CONSTRAINT pieces_status_check CHECK (status IN ('draft', 'available', 'reserved', 'sold', 'archived')),
    CONSTRAINT pieces_sold_at_status_check CHECK (sold_at IS NULL OR status = 'sold'),
    CONSTRAINT pieces_category_size_allowed_fkey FOREIGN KEY (category_slug, size_label) REFERENCES public.category_size_options (category_slug, size) ON UPDATE CASCADE
);

COMMENT ON TABLE public.pieces IS 'One-of-one clothing and accessory pieces in the Onesbryne catalog.';

COMMENT ON COLUMN public.pieces.code_number IS 'Internal numeric sequence for stable OB-### references.';

COMMENT ON COLUMN public.pieces.code IS 'Generated public catalog reference such as OB-001.';

COMMENT ON COLUMN public.pieces.price_cents IS 'Price stored in minor currency units to avoid decimal rounding issues.';

COMMENT ON COLUMN public.pieces.size_label IS 'Canonical size enum code. The frontend maps this to a display label.';

COMMENT ON COLUMN public.pieces.condition_label IS 'Canonical condition enum code. The frontend maps this to a display label.';

COMMENT ON COLUMN public.pieces.status IS 'Catalog lifecycle. Draft and archived pieces are admin-only.';

ALTER TABLE public.pieces ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Visible pieces are readable by everyone" ON public.pieces
    FOR SELECT TO anon, authenticated
    USING (status IN ('available', 'reserved', 'sold'));

CREATE POLICY "Admins can manage pieces" ON public.pieces
    FOR ALL TO authenticated
    USING (private.is_admin ())
    WITH CHECK (private.is_admin ());

GRANT SELECT ON TABLE public.pieces TO anon, authenticated, service_role;

GRANT INSERT (name, brand, category_slug, size_label, condition_label, price_cents, description, status, published_at, sold_at, updated_at) ON TABLE public.pieces TO authenticated;

GRANT UPDATE (name, brand, category_slug, size_label, condition_label, price_cents, description, status, published_at, sold_at, updated_at) ON TABLE public.pieces TO authenticated;

GRANT DELETE ON TABLE public.pieces TO authenticated;

GRANT INSERT, UPDATE, DELETE ON TABLE public.pieces TO service_role;

GRANT USAGE, SELECT ON SEQUENCE public.pieces_code_number_seq
    TO authenticated, service_role;

CREATE INDEX pieces_visible_created_idx ON public.pieces (status, created_at DESC)
WHERE
    status IN ('available', 'reserved', 'sold');

CREATE INDEX pieces_category_status_idx ON public.pieces (category_slug, status, created_at DESC);

CREATE INDEX pieces_price_idx ON public.pieces (price_cents);

CREATE TRIGGER maintain_piece_updated_at
    BEFORE UPDATE ON public.pieces
    FOR EACH ROW
    EXECUTE FUNCTION private.maintain_updated_at ();
